pages/urls.py
from django.urls import path
from . import views #use this, and then just do views.viewname


# if you use this -> from . import views 
# then you just do views.viewname in urlpattern path('', views.IndexView.as_view(), name='index'),

app_name = 'pages'
urlpatterns = [
    path('', views.indexPageView, name='index'),   
    path("about/", views.aboutPageView, name="about"),    
    path("login/", views.loginPageView, name="login"), 
    path("register/", views.register_request, name='register'),
    path("logout/",views.logout_view,name='logout'),
    path("generate_qr/",views.qr_code, name='generate_qr'),
    path('bioCreate/', views.bio_create_view, name='bio-create'),
    path('bioView/', views.bio_list_view, name='biophy-list'),
    path('<int:pk>/bioUpdate/', views.bio_update_view, name='bio-update'),
    path('<int:pk>/bioDelete/', views.bio_delete_view, name='bio-delete'),
    path("<int:pk>/showBio/", views.showSingleProfile, name='showSingleProfile'),
    #path("profile/<str:person_name>", views.profilePageView, name="profile")
]  

#Ignore the line below for now
#path('<int:pk>/', views.DetailView.as_view(), name='detail'),

qrmyancestors/urls.py
from django.contrib import admin
from django.urls import path, include
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]      

pages/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# class User(models.Model):
#     first_name = models.CharField(max_length=30)
#     last_name = models.CharField(max_length=30)
#     email = models.EmailField(max_length=50)
#     login = models.CharField(max_length=30)
#     password = models.CharField(max_length=20)
#     phone = models.CharField(max_length=10) 
#     class Meta:
#         db_table = 'user'
    
#     def __str__(self):
#         return f'{self.first_name, self.last_name, self.email, self.login, self.password, self.phone}'

class Deceased(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    gender = models.CharField(max_length=1)
    birthdate = models.DateField()
    birth_city = models.CharField(max_length=30)
    birth_state = models.CharField(max_length=30)
    birth_country = models.CharField(max_length=30)
    deathdate= models.DateField()
    death_city = models.CharField(max_length=30)
    death_state = models.CharField(max_length=30)
    death_country = models.CharField(max_length=30)
    bio = models.TextField()

    objects = models.Manager()
    class Meta:
        db_table = 'deceased'

    
    def __str__(self):
        return f'{self.first_name, self.last_name, self.gender, self.birthdate, self.birth_city, self.birth_state, self.birth_country, self.deathdate, self.death_city, self.death_state, self.death_country}'





   

pages/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Deceased



# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=True)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class DeceasedForm(forms.ModelForm):
    class Meta:
        model = Deceased
        fields = ('first_name', 'last_name', 'gender', 'birthdate', 'birth_city', 'birth_state',
        'birth_country', 'deathdate', 'death_city', 'death_state', 'death_country','bio')

pages/views.py
# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect  
from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
import qrcode
from PIL import Image
from .models import Deceased
from .forms import DeceasedForm
from django.contrib.auth.models import User
#from django.views import generic

#if request.user.is_authenticated:
    # Do something for authenticated users.
    
#else:
    # Do something for anonymous users.
    

#from django.views import generic


# Create your views here.

def indexPageView(request) :
    return render(request, 'pages/index.html') 
 
def aboutPageView(request) :
    return render(request, 'pages/about.html')

def loginPageView(request) :
    
    if request.method == "POST":
        sUsername = request.POST['usn']
        sPassword = request.POST['psw']
        user = authenticate(request, username=sUsername, password=sPassword)
        if user is not None:
            
            login(request, user)
            # Redirect to a success page.
            response = HttpResponseRedirect('/bioView/')
            return response
            
        else:
            print("Failed")
            context = {'failed':True}
            return render(request, 'pages/login.html',context)
    else:
        return render(request, 'pages/login.html')

# View to display the form for creating a new biography profile
def bio_create_view(request):
    form = DeceasedForm()
    if request.method == 'POST':
        f = DeceasedForm(request.POST)
        if f.is_valid():
            print(request.user.id)
            new_bio = f.save(commit=False)
            new_bio.user_id = request.user.id
            new_bio.save()
            return redirect('/bioView/')
    context = {
        'form': form
    }
    return render(request, 'pages/bioCreate.html', context)

# View to handle the submission of the form and create a new biography profile in the database
def bio_list_view(request):
    thisUser = request.user.id
    
    #entries = Journal_Line_Item.objects.filter(user=thisUser)
    biographies = Deceased.objects.filter(user_id = thisUser)
    context = {
        'biographies': biographies
    }
    return render(request, 'pages/bioList.html', context)

# View to display the form for updating an existing biography profile
def bio_update_view(request, pk):
    biography = Deceased.objects.get(pk=pk)
    form = DeceasedForm(instance=biography)
    
    if request.method == 'POST':
        form = DeceasedForm(request.POST, instance=biography)
        if form.is_valid():
            form.save()
            return redirect('/bioView/')
    context = {
        'form': form
    }
    return render(request, 'pages/bioUpdate.html', context)

# View to handle the submission of the form and update the existing biography profile in the database
def bio_delete_view(request, pk):
    biography = Deceased.objects.get(pk=pk)
    
    if request.method == 'POST':
        biography.delete()
        return redirect('/bioView/')
    context = {
        'biography' : biography
    }
    
    return render(request, 'pages/bioDelete.html', context)
    
def showSingleProfile(request, pk):
    biography = Deceased.objects.get(pk=pk)
   
    context = {
        'biography' : biography
    }
    return render(request, 'pages/viewonebio.html', context) 

def qr_code(request):
    url = request.build_absolute_uri()
    img = qrcode.make(url)
    response = HttpResponse(content_type="image/png")
    img.save(response, "PNG")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

def logout_view(request):
    logout(request)
    return redirect('/')

def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            
            form.save()
            
            messages.success(request, "Registration successful." )
            return redirect('/login/')
        else:
            print('failed')
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render (request, "pages/register.html", context={"register_form":form})


# def bio_create_view(request):
#     form = DeceasedForm()
#     if request.method == 'POST':
#         form = DeceasedForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('/bioView/')
#     context = {
#         'form': form
#     }
#     return render(request, 'pages/bioCreate.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html style="font-size: 16px;" lang="en"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="​Brilliant ideas!, Innovative Business is Our Sphere, ​We design digital products and brands, ​Quick, Smart &amp;amp; Great Solutions, ​We posit that good ideas can come from anywhere, ​Do you need professionals for your next construction project?, Benefits of working with us​, 01, 02, 03, 04, 05, 06, ​Small Pricing Plan For Your Creative Business, ​Branding Agency">
    <meta name="description" content="">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static '/nicepage.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'js/jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>
    <meta name="generator" content="Nicepage 5.1.5, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu:300,300i,400,400i,500,500i,700,700i">

    {% block link %}{% endblock %}
    
    {% block head %}
    {% endblock %}

    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "qrancestors"
}</script>
    <meta name="theme-color" content="#4894b6">
    <meta property="og:title" content="home">
    <meta property="og:description" content="">
    <meta property="og:type" content="website">
</head>

<body class="u-body u-xl-mode" data-lang="en">

{% comment %} HEADER {% endcomment %}

<header class="u-clearfix u-grey-80 u-header u-header" id="sec-9ee4"><nav class="u-align-left u-menu u-menu-dropdown u-menu-open-right u-offcanvas u-menu-1" data-responsive-from="MD">
  <div class="menu-collapse">
    <a class="u-button-style u-custom-text-hover-color u-nav-link u-palette-1-base" href="#" style="font-size: calc(1em + 8px); background-image: none;">
      <svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 302 302" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-5c50"></use></svg>
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="svg-5c50" x="0px" y="0px" viewBox="0 0 302 302" style="enable-background:new 0 0 302 302;" xml:space="preserve" class="u-svg-content"><g><rect y="36" width="302" height="30"></rect><rect y="236" width="302" height="30"></rect><rect y="136" width="302" height="30"></rect>
</g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g></svg>
    </a>
  </div>
  <div class="u-custom-menu u-nav-container">
    <ul class="u-nav u-unstyled u-nav-1">
      <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-1-light-2" href="{% url 'pages:index' %}" style="padding: 10px 20px;">Home</a></li>
      <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-1-light-2" href="{% url 'pages:about' %}" style="padding: 10px 20px;">About Us</a></li>
      
      {% if user.is_authenticated %}
      <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-1-light-2" href="{% url 'pages:biophy-list' %}" style="padding: 10px 20px;">My Ancestors</a></li>
      <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-1-light-2" href="{% url 'pages:logout' %}" style="padding: 10px 20px;">Logout</a></li>
      {% else %}
      <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-1-light-2" href="{% url 'pages:login' %}" style="padding: 10px 20px;">Login</a></li>
      {%endif%}
    </ul>
  </div>
  <div class="u-custom-menu u-nav-container-collapse">
    <div class="u-align-center u-container-style u-custom-color-1 u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
      <div class="u-inner-container-layout u-sidenav-overflow">
        <div class="u-menu-close"></div>
        <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2">
          <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'pages:index' %}">Home</a></li>
          <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'pages:about' %}">About Us</a></li>
          {% if user.is_authenticated %}
          <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'pages:logout' %}">Logout</a></li>
          <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'pages:biophy-list' %}">My Ancesrots</a></li>
          {% else %}
          <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'pages:login' %}">Login</a></li>
          {%endif%}
        </ul>
      </div>
    </div>
    <div class="u-custom-color-2 u-menu-overlay u-opacity u-opacity-70"></div>
  </div>
</nav>
    <img class="u-image u-image-contain u-image-default u-image-1" src="{% static 'images/QRmyAncestorslogos.png' %}" alt="" data-image-width="980" data-image-height="200">
</header>

{% comment %} END HEADER {% endcomment %}
    
{% block content %}
{% endblock %}

<script>
  {% block js_scripts %}{% endblock %}
</script> 
    
    
<footer class="u-align-center u-clearfix u-custom-color-2 u-footer u-footer" id="sec-32b4"><div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
  <p class="u-small-text u-text u-text-variant u-text-1"> © 2022 QRmyAncestors</p>
</div></footer>

  
</body>
</html>

templates/oldbase.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="INTUITIVE">
    <meta name="description" content="">
    <link rel="stylesheet" href="{% static '/nicepage.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'nicepage.js' %}" defer=""></script>
  </head>
  <body class="u-body u-xl-mode" data-lang="en">
    <header class="u-clearfix u-grey-80 u-header u-header" id="sec-8529"><div class="u-clearfix u-sheet u-sheet-1">
        <a href="#" class="u-image u-logo u-image-1" data-image-width="980" data-image-height="200">
          <img src="{% static 'images/QRmyAncestors-logos_white1.png' %}" class="u-logo-image u-logo-image-1">
        </a>
        <nav class="u-menu u-menu-one-level u-offcanvas u-menu-1">
          <div class="u-custom-menu u-nav-container">
            <ul class="u-nav u-unstyled u-nav-1">
              <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'pages:index' %}" style="padding: 10px 20px;">Home</a></li>
              <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'pages:ancestors' %}" style="padding: 10px 20px;">My Ancestors</a></li>
              <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'pages:about' %}" style="padding: 10px 20px;">About Us</a></li>
              {% if user.is_authenticated %}
                <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'pages:logout' %}" style="padding: 10px 20px;">Logout</a></li>
              {% else %}
                <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'pages:login' %}" style="padding: 10px 20px;">Login</a></li>
              {%endif%}
    </header>

    
{% block content %}
{% endblock %}

    <footer text-align: center; class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-0800">
      <div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1">© 2022 QRmyAncestors</p>
      </div>
    </footer>  
  </body>
</html>

templates/pages/biography.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        form {
            width: 500px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
        }
        form label {
            display: block;
            margin-bottom: 10px;
        }
        form input, form textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        form button {
            margin-top: 20px;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: white;
            font-weight: bold;
            cursor: pointer;
        }
    </style>
    
</head>
<body>
    <h1>Biography Profile</h1>

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Submit</button>
</form>
    
</body>
</html>

templates/pages/index.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block link %} <link rel="stylesheet" href="../../static/css/index.css" media="screen"> {% endblock %}

{% load static %}
{% block content %}

<section class="u-clearfix u-image u-section-1" id="sec-9e56" data-image-width="1280" data-image-height="853">
  <div class="u-clearfix u-sheet u-sheet-1">
    <div class="u-bottom-right-radius-50 u-container-style u-group u-shape-round u-top-right-radius-50 u-white u-group-1" data-animation-name="customAnimationIn" data-animation-duration="2000">
      <div class="u-container-layout u-container-layout-1">
        <h2 class="u-custom-font u-font-ubuntu u-text u-text-custom-color-1 u-text-default u-text-1" spellcheck="false">Who We Are</h2>
        <p class="u-text u-text-default u-text-2" spellcheck="false"> We are on a mission to connect people with<br>their past on a new level.&nbsp;
        </p>
        <a href="{% url 'pages:about' %}" class="u-border-2 u-border-grey-75 u-btn u-btn-round u-button-style u-custom-color-1 u-hover-palette-1-light-2 u-radius-50 u-btn-1">Learn More</a>
      </div>
    </div>
  </div>
</section>
<section class="u-align-center u-clearfix u-container-align-center-md u-container-align-center-sm u-container-align-center-xs u-white u-section-2" id="carousel_00fd">
  <div class="u-clearfix u-sheet u-sheet-1">
    <h2 class="u-align-center-md u-align-center-sm u-align-center-xs u-custom-font u-font-ubuntu u-text u-text-palette-1-base u-text-1" spellcheck="false">Technology has already helped connect us with our loved ones who have passed on. Why not add to it?</h2>
    <p class="u-align-center-md u-align-center-sm u-align-center-xs u-large-text u-text u-text-variant u-text-2" spellcheck="false">With QR my ancestors, you have the choice to spread the inspiring stories of those before with:</p>
    <div class="u-list u-list-1">
      <div class="u-repeater u-repeater-1">
        <div class="u-align-center u-container-style u-custom-color-1 u-list-item u-repeater-item u-shape-rectangle u-list-item-1">
          <div class="u-container-layout u-similar-container u-valign-bottom u-container-layout-1">
            <p class="u-align-center u-custom-font u-font-ubuntu u-text u-text-default u-text-3">Gravesite QR Codes</p>
            <div class="u-image u-image-circle u-preserve-proportions u-image-1" alt="" data-image-width="1280" data-image-height="1280"></div>
          </div>
        </div>
        <div class="u-align-center u-container-style u-custom-color-1 u-list-item u-repeater-item u-shape-rectangle u-list-item-2">
          <div class="u-container-layout u-similar-container u-valign-bottom u-container-layout-2">
            <p class="u-align-center u-custom-font u-font-ubuntu u-text u-text-default u-text-4" spellcheck="false">Ancestor Database</p>
            <div class="u-image u-image-circle u-preserve-proportions u-image-2" alt="" data-image-width="1280" data-image-height="813"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
  

{% endblock %}

templates/prevbase.html
{% load static %}
<!DOCTYPE html>
<html style="font-size: 16px;" lang="en"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="​Brilliant ideas!, Innovative Business is Our Sphere, ​We design digital products and brands, ​Quick, Smart &amp;amp; Great Solutions, ​We posit that good ideas can come from anywhere, ​Do you need professionals for your next construction project?, Benefits of working with us​, 01, 02, 03, 04, 05, 06, ​Small Pricing Plan For Your Creative Business, ​Branding Agency">
    <meta name="description" content="">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static '/nicepage.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'js/jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>
    <meta name="generator" content="Nicepage 5.1.5, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu:300,300i,400,400i,500,500i,700,700i">
    <!--pages/static/images/QRmyAncestorslogos.png-->
    {% block link %}{% endblock %}
    
    {% block head %}
    {% endblock %}

    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "qrancestors"
}</script>
    <meta name="theme-color" content="#4894b6">
    <meta property="og:title" content="Home">
    <meta property="og:description" content="">
    <meta property="og:type" content="website">
    <script>{% block headjs %}{% endblock %}</script>
</head>

<body data-home-page="Home.html" data-home-page-title="Home" class="u-body u-xl-mode" data-lang="en">


{% comment %} HEADER {% endcomment %}

    <header class="u-clearfix u-grey-80 u-header u-header" id="sec-9ee4"><nav class="u-align-left u-menu u-menu-hamburger u-menu-open-right u-offcanvas u-menu-1" data-responsive-from="XL">
        <div class="menu-collapse">
          <a class="u-button-style u-nav-link" href="#" style="padding: 4px 0px; font-size: calc(1em + 8px);">
            <svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 302 302" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-5c50"></use></svg>
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="svg-5c50" x="0px" y="0px" viewBox="0 0 302 302" style="enable-background:new 0 0 302 302;" xml:space="preserve" class="u-svg-content"><g><rect y="36" width="302" height="30"></rect><rect y="236" width="302" height="30"></rect><rect y="136" width="302" height="30"></rect>
</g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g></svg>
          </a>
        </div>
        <div class="u-custom-menu u-nav-container">
          <ul class="u-nav u-unstyled u-nav-1"><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="Home.html" style="padding: 10px 20px;">Home</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="Login2.html" style="padding: 10px 20px;">Login</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="My-Ancestors.html" style="padding: 10px 20px;">My Ancestors</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="About-Us.html" style="padding: 10px 20px;">About Us</a>
</li></ul>
        </div>
        <div class="u-custom-menu u-nav-container-collapse">
          <div class="u-align-center u-container-style u-custom-color-1 u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
            <div class="u-inner-container-layout u-sidenav-overflow">
              <div class="u-menu-close"></div>
              <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2">
                <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'pages:index' %}" style="padding: 10px 20px;">Home</a></li>
                {% if user.is_authenticated %}
                <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'pages:ancestors' %}" style="padding: 10px 20px;">My Ancestors</a></li>
                {%endif%}
                
                <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'pages:about' %}" style="padding: 10px 20px;">About Us</a></li>
                {% if user.is_authenticated %}
                  <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'pages:logout' %}" style="padding: 10px 20px;">Logout</a></li>
                {% else %}
                  <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'pages:login' %}" style="padding: 10px 20px;">Login</a></li>
                {%endif%}
            </ul>
            </div>
          </div>
          <div class="u-custom-color-2 u-menu-overlay u-opacity u-opacity-70"></div>
        </div> 
      </nav>
      <img class="u-image u-image-contain u-image-default u-image-1" src="{% static 'images/QRmyAncestorslogos.png' %}" alt="" data-image-width="980" data-image-height="200">
    </header>
    
{% comment %} END HEADER {% endcomment %}
    
{% block content %}
{% endblock %}

<script>
  {% block js_scripts %}{% endblock %}
</script> 
    
    
    <footer class="u-align-center u-clearfix u-custom-color-2 u-footer u-footer" id="sec-32b4"><div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1"> © 2022 QRmyAncestors</p>
      </div>
    </footer>

  
</body>
</html>